apiVersion: alertmanager.mimir.m.dip.io/v1alpha1
kind: Config
metadata:
  name: example-alertmanager-config-ns
  namespace: default
spec:
  forProvider:
    # Configuration for Grafana Mimir Alertmanager
    receiver:
    - name: default
    route:
    - receiver: default
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
